nox > Running session test-3.13
nox > Creating virtual environment (virtualenv) using python3.13 in .nox/test-3-13
nox > python -m pip install -e .
nox > python -m pip install pytest pytest-cov pytest-flask pytest-mock
nox > pytest tests/unit --cov=kiosk_show_replacement --cov-report=term-missing --cov-report=html:htmlcov --cov-fail-under=30 -v
============================= test session starts ==============================
platform linux -- Python 3.13.3, pytest-8.4.0, pluggy-1.6.0 -- /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/bin/python
cachedir: .pytest_cache
rootdir: /home/jantman/GIT/kiosk-show-replacement
configfile: pytest.ini
plugins: mock-3.14.1, cov-6.2.1, flask-1.3.0
collecting ... collected 49 items

tests/unit/test_app.py::TestAppFactory::test_create_app_default_config PASSED [  2%]
tests/unit/test_app.py::TestAppFactory::test_create_app_testing_config PASSED [  4%]
tests/unit/test_app.py::TestAppFactory::test_app_has_blueprints PASSED   [  6%]
tests/unit/test_app.py::TestAppFactory::test_database_initialization PASSED [  8%]
tests/unit/test_app.py::TestAppFactory::test_health_check_endpoint PASSED [ 10%]
tests/unit/test_app.py::TestAppConfiguration::test_instance_path_creation PASSED [ 12%]
tests/unit/test_app.py::TestAppConfiguration::test_default_configuration_values PASSED [ 14%]
tests/unit/test_app.py::TestAppConfiguration::test_environment_variable_override PASSED [ 16%]
tests/unit/test_app.py::TestAppExtensions::test_sqlalchemy_initialization PASSED [ 18%]
tests/unit/test_app.py::TestAppExtensions::test_migrate_initialization PASSED [ 20%]
tests/unit/test_app.py::TestAppExtensions::test_cors_initialization PASSED [ 22%]
tests/unit/test_models.py::TestUserModel::test_create_user PASSED        [ 24%]
tests/unit/test_models.py::TestUserModel::test_user_password_hashing PASSED [ 26%]
tests/unit/test_models.py::TestUserModel::test_user_repr PASSED          [ 28%]
tests/unit/test_models.py::TestUserModel::test_user_to_dict PASSED       [ 30%]
tests/unit/test_models.py::TestUserModel::test_username_validation PASSED [ 32%]
tests/unit/test_models.py::TestUserModel::test_email_validation PASSED   [ 34%]
tests/unit/test_models.py::TestUserModel::test_unique_constraints PASSED [ 36%]
tests/unit/test_models.py::TestDisplayModel::test_create_display PASSED  [ 38%]
tests/unit/test_models.py::TestDisplayModel::test_display_repr PASSED    [ 40%]
tests/unit/test_models.py::TestDisplayModel::test_display_to_dict PASSED [ 42%]
tests/unit/test_models.py::TestDisplayModel::test_display_online_status PASSED [ 44%]
tests/unit/test_models.py::TestDisplayModel::test_display_heartbeat_update PASSED [ 46%]
tests/unit/test_models.py::TestDisplayModel::test_display_unique_name_per_owner PASSED [ 48%]
tests/unit/test_models.py::TestDisplayModel::test_display_owner_relationship PASSED [ 51%]
tests/unit/test_models.py::TestSlideshowModel::test_create_slideshow PASSED [ 53%]
tests/unit/test_models.py::TestSlideshowModel::test_slideshow_repr PASSED [ 55%]
tests/unit/test_models.py::TestSlideshowModel::test_slideshow_to_dict PASSED [ 57%]
tests/unit/test_models.py::TestSlideshowModel::test_slideshow_item_count_property PASSED [ 59%]
tests/unit/test_models.py::TestSlideshowModel::test_slideshow_total_duration_property PASSED [ 61%]
tests/unit/test_models.py::TestSlideshowModel::test_slideshow_items_relationship PASSED [ 63%]
tests/unit/test_models.py::TestSlideshowModel::test_slideshow_unique_name_per_owner PASSED [ 65%]
tests/unit/test_models.py::TestSlideshowModel::test_slideshow_owner_relationship PASSED [ 67%]
tests/unit/test_models.py::TestSlideshowItemModel::test_create_slideshow_item PASSED [ 69%]
tests/unit/test_models.py::TestSlideshowItemModel::test_slideshow_item_repr PASSED [ 71%]
tests/unit/test_models.py::TestSlideshowItemModel::test_slideshow_item_to_dict PASSED [ 73%]
tests/unit/test_models.py::TestSlideshowItemModel::test_slideshow_item_content_types PASSED [ 75%]
tests/unit/test_models.py::TestSlideshowItemModel::test_slideshow_item_content_type_validation PASSED [ 77%]
tests/unit/test_models.py::TestSlideshowItemModel::test_slideshow_item_url_validation PASSED [ 79%]
tests/unit/test_models.py::TestSlideshowItemModel::test_slideshow_item_slideshow_relationship PASSED [ 81%]
tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_slideshow_items PASSED [ 83%]
tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_displays PASSED [ 85%]
tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows PASSED [ 87%]
tests/unit/test_models.py::TestModelRelationships::test_audit_fields_auto_update PASSED [ 89%]
tests/unit/test_models.py::TestModelRelationships::test_foreign_key_constraints PASSED [ 91%]
tests/unit/test_models.py::TestDatabaseUtilityMethods::test_user_password_methods PASSED [ 93%]
tests/unit/test_models.py::TestDatabaseUtilityMethods::test_display_heartbeat_methods PASSED [ 95%]
tests/unit/test_models.py::TestDatabaseUtilityMethods::test_model_serialization PASSED [ 97%]
tests/unit/test_models.py::TestDatabaseUtilityMethods::test_model_string_representations PASSED [100%]

=============================== warnings summary ===============================
tests/unit/test_models.py::TestDisplayModel::test_display_unique_name_per_owner
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/werkzeug/routing/rules.py:837: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a50d9990>
    code = compile(module, "<werkzeug routing>", "exec")
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestDisplayModel::test_display_unique_name_per_owner
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/werkzeug/routing/rules.py:837: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a50db2e0>
    code = compile(module, "<werkzeug routing>", "exec")
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a50d9120>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a50da110>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a50d94e0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a50daf20>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4f38400>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4f3ad40>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a50084f0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a500a7a0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4f39990>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a50095d0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a5009f30>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a500bd30>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4ed8e50>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4eda5c0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4edb6a0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4d9ca90>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4d9e110>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4d9f970>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4c64310>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4c65f30>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4c674c0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4cdf1f0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4cdc8b0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4cde110>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4cdfd30>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/unit/test_models.py::TestModelRelationships::test_cascade_delete_user_slideshows
  /home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:527: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4a695d0>
    ctr = cls.__dict__.get("__init__", False)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================ tests coverage ================================
_______________ coverage: platform linux, python 3.13.3-final-0 ________________

Name                                           Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------
kiosk_show_replacement/__init__.py                10      0   100%
kiosk_show_replacement/api/__init__.py            67     50    25%   31-32, 38-51, 57-64, 71-93, 99-121, 127-136
kiosk_show_replacement/app.py                     31      0   100%
kiosk_show_replacement/auth/__init__.py            1      1     0%   15
kiosk_show_replacement/cli/__init__.py             1      0   100%
kiosk_show_replacement/cli/init_db.py             83     67    19%   39-101, 129-176
kiosk_show_replacement/cli/init_db_new.py         83     83     0%   10-176
kiosk_show_replacement/cli/main.py                35     15    57%   17, 28-32, 41-44, 53-61, 66
kiosk_show_replacement/config/__init__.py         21     21     0%   7-55
kiosk_show_replacement/database_utils.py         182    142    22%   30-36, 41-47, 57-95, 116-144, 157-290, 299-302, 307-310, 315-320, 325-328, 335-343, 350-360, 365, 392-421, 434-462
kiosk_show_replacement/display/__init__.py        19      8    58%   32-33, 39-46, 52-59
kiosk_show_replacement/migration_utils.py         78     78     0%   8-173
kiosk_show_replacement/models/__init__.py        222     24    89%   105, 120, 189, 200, 214, 243, 245, 252, 320, 345, 353, 355, 362, 368-373, 428, 434, 437-439, 483, 490
kiosk_show_replacement/slideshow/__init__.py      43     30    30%   31-32, 38-59, 65-72, 78-89
kiosk_show_replacement/static/__init__.py          0      0   100%
kiosk_show_replacement/templates/__init__.py       0      0   100%
kiosk_show_replacement/utils/__init__.py          46     46     0%   8-129
----------------------------------------------------------------------------
TOTAL                                            922    565    39%
Coverage HTML written to dir htmlcov
/home/jantman/GIT/kiosk-show-replacement/.nox/test-3-13/lib/python3.13/site-packages/_pytest/unraisableexception.py:31: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7f45a4d9dc60>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Required test coverage of 30% reached. Total coverage: 38.72%
======================= 49 passed, 28 warnings in 42.99s =======================
nox > Session test-3.13 was successful.
